name: Oasys Blockscout Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    env:
      DOCKER_CHAIN_NAME: oasys
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version and SHA from tag
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          
          RELEASE_VERSION=$(echo $TAG | cut -d'-' -f1)
          SHORT_SHA=$(echo $TAG | cut -d'-' -f2)
          
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "SHORT_SHA=$SHORT_SHA"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bibi4c/blockscout-v6-frontend:${{ env.RELEASE_VERSION }}-${{ env.SHORT_SHA }}
          labels: https://github.com/bibi4c/blockscout-v6-frontend
          platforms: linux/arm64/v8